name: Build .so File

on:
  push:
    branches:
      - main  # 触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
        unzip android-ndk-r21d-linux-x86_64.zip -d $HOME/ndk
        export ANDROID_NDK_HOME=$HOME/ndk/android-ndk-r21d
        export PATH=$ANDROID_NDK_HOME:$PATH

    - name: Build .so file
      run: |
        cd keychain_jni/jni  # 进入文件所在路径
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk NDK_DEBUG=0

    - name: Move .so file to root
      run: |
        mv libs/armeabi-v7a/libkeychain.so .  # 移动 .so 文件到根目录

    - name: Upload .so file
      uses: actions/upload-artifact@v2
      with:
        name: my-library
        path: libkeychain.so
